In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [2]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [3]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [4]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [5]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [6]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

In [8]:
from sklearn.linear_model import SGDClassifier
LogisticRegression_1 = SGDClassifier(loss='log')
SVM_1 = SGDClassifier(loss="hinge")

LogisticRegression_1.fit(X,Y)
SVM_1.fit(X,Y)

print(LogisticRegression_1.coef_)
print(SVM_1.coef_)

[[14946.94912062 -1790.77378085  9439.41502881]]
[[19813.5573961  -6863.75442442 10171.09668174]]


## Observation

From the output above, we can see that, for both Logistic Regression and SVM, feature 1 has the highest impact to classify the dependent variable (Y). Before we accept this as our "best" model, we have to make sure that this model is actually legit. One of the thing that we should look at is the variance of each feature. If features has extremely different variance, it might be a mistake to not standardize these features in advance. We know that feature 2 has the highest variance, and then feature 1 and feature 3 respectively. Since the variances are not the same amongst feature, it is important to standardize the data. Otherwise, the feature importance (.coef_) will not make sense.

To illustrate this further, looking at the correlation, feature 3 is the most correlated feature to the dependent variable. Thus, feature 3 should have the highest weight amongst other features. However, since the features are not standardized, we see that feature 1 has the highest weight instead. 

We will discuss this further in the observation below

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

LogisticRegression_2 = SGDClassifier(loss='log')
SVM_2 = SGDClassifier(loss="hinge")

LogisticRegression_2.fit(X_scaled,Y)
SVM_2.fit(X_scaled,Y)

print(LogisticRegression_2.coef_)
print(SVM_2.coef_)

[[0.37776693 0.95457499 9.24029721]]
[[-2.33145406  1.88953376 18.28793816]]


<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

## Observation (cont..)

Now that we have standardize the data, we can see that feature 3 has the highest weight. This fact justify our correlation matrix. To conclude, we have to standardize the data when the variance amongst feature differ by a lot. 