<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [30]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [158]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)

In [159]:
from sklearn.model_selection import train_test_split 
x, x_test, y, y_test = train_test_split (X,y, test_size=0.2, train_size=0.8 )
x_train, x_cv, y_train, y_cv = train_test_split(x,y,test_size = 0.25, train_size =0.75)

In [198]:
clf = SVC(gamma = 0.001, C=100, random_state = 7)
clf.fit(x_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=7, shrinking=True, tol=0.001,
    verbose=False)

In [163]:
clf.decision_function(x_cv)

array([-2.57463800e+00, -1.82232960e+00, -2.65223514e+00, -2.62951012e+00,
       -3.55136263e+00,  1.53082124e+00, -1.93158819e+00,  1.71616352e+00,
       -3.24615433e+00,  1.75518204e+00, -1.92898337e+00,  9.29804561e-01,
       -2.28326203e+00, -3.47104530e+00, -4.32849183e+00, -2.36488835e+00,
        1.75084839e+00,  2.27457941e+00,  1.85652750e+00,  1.90366607e+00,
       -1.14806849e-01, -3.27193926e+00, -2.30867747e+00, -3.02098803e+00,
       -1.96542611e+00, -4.19181958e+00,  1.32367762e+00, -2.93461272e+00,
        2.29102600e-01, -3.04023069e+00,  1.07897533e+00, -2.96276200e+00,
       -2.92328222e+00, -1.99178121e+00, -2.32860913e-01,  3.85018521e-01,
       -1.70072224e+00,  1.66726145e+00, -3.41951275e+00,  1.61539505e+00,
       -3.44192309e+00,  2.23479270e+00, -1.74239380e+00,  1.14387877e+00,
       -2.68917459e+00,  1.25972795e+00, -1.70527396e+00, -3.14112465e+00,
        1.62461022e+00,  1.69315782e+00,  1.06685386e+00, -2.99349347e+00,
       -1.94300419e+00,  

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [210]:
def decision_function(x_cv):
    alphas = clf.dual_coef_[0]
    decision_function = []
    for Xq in x_cv:
        sum = clf.intercept_[0]
        for i,supvec in enumerate(clf.support_vectors_):
            norm = np.linalg.norm(supvec - Xq)**2
            kernel = np.exp(-0.001*norm)
            #print(kernel)
            sum += (alphas[i]*kernel)
        #print(sum)
        decision_function.append(sum)
        
    return np.array(decision_function)

In [211]:
decision_function(x_cv)

array([-2.57463800e+00, -1.82232960e+00, -2.65223514e+00, -2.62951012e+00,
       -3.55136263e+00,  1.53082124e+00, -1.93158819e+00,  1.71616352e+00,
       -3.24615433e+00,  1.75518204e+00, -1.92898337e+00,  9.29804561e-01,
       -2.28326203e+00, -3.47104530e+00, -4.32849183e+00, -2.36488835e+00,
        1.75084839e+00,  2.27457941e+00,  1.85652750e+00,  1.90366607e+00,
       -1.14806849e-01, -3.27193926e+00, -2.30867747e+00, -3.02098803e+00,
       -1.96542611e+00, -4.19181958e+00,  1.32367762e+00, -2.93461272e+00,
        2.29102600e-01, -3.04023069e+00,  1.07897533e+00, -2.96276200e+00,
       -2.92328222e+00, -1.99178121e+00, -2.32860913e-01,  3.85018521e-01,
       -1.70072224e+00,  1.66726145e+00, -3.41951275e+00,  1.61539505e+00,
       -3.44192309e+00,  2.23479270e+00, -1.74239380e+00,  1.14387877e+00,
       -2.68917459e+00,  1.25972795e+00, -1.70527396e+00, -3.14112465e+00,
        1.62461022e+00,  1.69315782e+00,  1.06685386e+00, -2.99349347e+00,
       -1.94300419e+00,  

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

In [230]:
#calculating Y+ and Y-
Np, Nn = np.unique(y_train, return_counts=True)[1]
Yp = (Np+1)/(Np+2)
Yn = 1/(Nn+2)

ycv_new = []

#Converting 0s and 1s in Y_CV to Y+ or Y-
for y in y_cv:
    if y == 0:
        ycv_new.append(Yn)
    else:
        ycv_new.append(Yp)

In [342]:
def initialize_weights(dim):
    ''' In this function, we will initialize our weights and bias'''
    #initialize the weights to zeros array of (1,dim) dimensions
    #you use zeros_like function to initialize zero, check this link https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html
    #initialize bias to zero
    w = np.zeros_like(dim).reshape(1,-1)
    b = 0

    return w,b

def sigmoid(z):
    ''' In this function, we will return sigmoid of z'''
    # compute sigmoid(z) and return
    result = 1/(1+np.exp(-z))
    return result

def logloss(y_true,y_pred):
    '''In this function, we will compute log loss '''
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    loss = -np.sum(y_true * np.log10(y_pred) + (1 - y_true) * np.log10(1 - y_pred))/len(y_true)
    return loss

def gradient_dw(x,y,w,b,alpha,N):
    '''In this function, we will compute the gardient w.r.to w '''
    dw = (x * (y- sigmoid((w@x)+b) )) - ((alpha/N)*w)
    return dw

def gradient_db(x,y,w,b):
    '''In this function, we will compute gradient w.r.to b '''
    db = y - sigmoid(w@x+b)
    return db

from tqdm import tqdm

def train(X_train,y_train,epochs,alpha,eta0):
    ''' In this function, we will implement logistic regression'''
    train_loss,test_loss = [],[]
    w,b = initialize_weights(X_train[0])
    #print("weight is {}".format(b))

    N = len(X_train)
    for epoch in tqdm(range(0,epochs)):
        for x,y in zip(X_train.reshape(-1,1),y_train.reshape(-1,1)):
            #print(x.shape)
            #print(y.shape)
            #print(w.shape)
            #print(b)
            gradw = gradient_dw(x,y,w,b,alpha,N)
            gradb = gradient_db(x,y,w,b)
            w += (eta0 * gradw)
            b += (eta0 * gradb)
       
        trainloss = logloss(y_train, 1/(1+np.exp(-(w * decision_function(X_train) + b))))
        train_loss.append(trainloss)
        print(f"Epoch {epoch+1}: Training loss: {trainloss}")
                
    return w,b

In [343]:
weight, bias = train(np.array(ycv_new), y_cv, 50, 0.0001, 0.0001)

  2%|▏         | 1/50 [00:04<03:53,  4.76s/it]

Epoch 1: Training loss: 0.29867417569558563


  4%|▍         | 2/50 [00:09<03:50,  4.80s/it]

Epoch 2: Training loss: 0.2964083671148156


  6%|▌         | 3/50 [00:14<03:47,  4.85s/it]

Epoch 3: Training loss: 0.29422969313477015


  8%|▊         | 4/50 [00:19<03:41,  4.82s/it]

Epoch 4: Training loss: 0.2921353661082111


 10%|█         | 5/50 [00:24<03:35,  4.80s/it]

Epoch 5: Training loss: 0.2901226858858137


 12%|█▏        | 6/50 [00:28<03:29,  4.77s/it]

Epoch 6: Training loss: 0.2881890380678522


 14%|█▍        | 7/50 [00:33<03:25,  4.79s/it]

Epoch 7: Training loss: 0.2863318921674281


 16%|█▌        | 8/50 [00:38<03:20,  4.78s/it]

Epoch 8: Training loss: 0.2845487997017492


 18%|█▊        | 9/50 [00:43<03:15,  4.77s/it]

Epoch 9: Training loss: 0.28283739222646265


 20%|██        | 10/50 [00:47<03:11,  4.78s/it]

Epoch 10: Training loss: 0.28119537932662503


 22%|██▏       | 11/50 [00:52<03:05,  4.77s/it]

Epoch 11: Training loss: 0.27962054657655405


 24%|██▍       | 12/50 [00:57<03:01,  4.78s/it]

Epoch 12: Training loss: 0.27811075347956193


 26%|██▌       | 13/50 [01:02<02:57,  4.80s/it]

Epoch 13: Training loss: 0.2766639313974079


 28%|██▊       | 14/50 [01:07<02:54,  4.85s/it]

Epoch 14: Training loss: 0.27527808147822463


 30%|███       | 15/50 [01:12<02:49,  4.83s/it]

Epoch 15: Training loss: 0.2739512725906818


 32%|███▏      | 16/50 [01:17<02:45,  4.87s/it]

Epoch 16: Training loss: 0.27268163927122135


 34%|███▍      | 17/50 [01:21<02:39,  4.85s/it]

Epoch 17: Training loss: 0.27146737969035917


 36%|███▌      | 18/50 [01:26<02:35,  4.85s/it]

Epoch 18: Training loss: 0.27030675364326917


 38%|███▊      | 19/50 [01:31<02:30,  4.85s/it]

Epoch 19: Training loss: 0.26919808056915456


 40%|████      | 20/50 [01:36<02:24,  4.80s/it]

Epoch 20: Training loss: 0.2681397376032705


 42%|████▏     | 21/50 [01:41<02:20,  4.85s/it]

Epoch 21: Training loss: 0.267130157664868


 44%|████▍     | 22/50 [01:45<02:14,  4.81s/it]

Epoch 22: Training loss: 0.2661678275838017


 46%|████▌     | 23/50 [01:50<02:10,  4.84s/it]

Epoch 23: Training loss: 0.2652512862680629


 48%|████▊     | 24/50 [01:55<02:05,  4.84s/it]

Epoch 24: Training loss: 0.2643791229140615


 50%|█████     | 25/50 [02:00<02:01,  4.86s/it]

Epoch 25: Training loss: 0.263549975261099


 52%|█████▏    | 26/50 [02:05<01:57,  4.90s/it]

Epoch 26: Training loss: 0.2627625278911189


 54%|█████▍    | 27/50 [02:10<01:54,  4.96s/it]

Epoch 27: Training loss: 0.2620155105745157


 56%|█████▌    | 28/50 [02:15<01:48,  4.92s/it]

Epoch 28: Training loss: 0.2613076966625051


 58%|█████▊    | 29/50 [02:20<01:42,  4.87s/it]

Epoch 29: Training loss: 0.26063790152631294


 60%|██████    | 30/50 [02:24<01:36,  4.83s/it]

Epoch 30: Training loss: 0.2600049810432266


 62%|██████▏   | 31/50 [02:29<01:31,  4.84s/it]

Epoch 31: Training loss: 0.2594078301293614


 64%|██████▍   | 32/50 [02:34<01:27,  4.84s/it]

Epoch 32: Training loss: 0.2588453813188314


 66%|██████▌   | 33/50 [02:39<01:22,  4.88s/it]

Epoch 33: Training loss: 0.2583166033888669


 68%|██████▊   | 34/50 [02:44<01:18,  4.89s/it]

Epoch 34: Training loss: 0.2578205000303009


 70%|███████   | 35/50 [02:49<01:14,  4.93s/it]

Epoch 35: Training loss: 0.257356108562738


 72%|███████▏  | 36/50 [02:54<01:09,  4.94s/it]

Epoch 36: Training loss: 0.2569224986936313


 74%|███████▍  | 37/50 [02:59<01:04,  4.93s/it]

Epoch 37: Training loss: 0.25651877132041523


 76%|███████▌  | 38/50 [03:04<00:58,  4.86s/it]

Epoch 38: Training loss: 0.25614405737478


 78%|███████▊  | 39/50 [03:08<00:53,  4.82s/it]

Epoch 39: Training loss: 0.25579751670812656


 80%|████████  | 40/50 [03:13<00:48,  4.80s/it]

Epoch 40: Training loss: 0.2554783370171928


 82%|████████▏ | 41/50 [03:18<00:43,  4.79s/it]

Epoch 41: Training loss: 0.25518573280881746


 84%|████████▍ | 42/50 [03:23<00:38,  4.83s/it]

Epoch 42: Training loss: 0.254918944402781


 86%|████████▌ | 43/50 [03:28<00:33,  4.82s/it]

Epoch 43: Training loss: 0.2546772369716495


 88%|████████▊ | 44/50 [03:32<00:28,  4.82s/it]

Epoch 44: Training loss: 0.2544598996165352


 90%|█████████ | 45/50 [03:37<00:24,  4.81s/it]

Epoch 45: Training loss: 0.25426624447768686


 92%|█████████▏| 46/50 [03:42<00:19,  4.79s/it]

Epoch 46: Training loss: 0.2540956058788216


 94%|█████████▍| 47/50 [03:47<00:14,  4.82s/it]

Epoch 47: Training loss: 0.25394733950411597


 96%|█████████▌| 48/50 [03:52<00:09,  4.80s/it]

Epoch 48: Training loss: 0.2538208216067861


 98%|█████████▊| 49/50 [03:56<00:04,  4.79s/it]

Epoch 49: Training loss: 0.25371544824819303


100%|██████████| 50/50 [04:01<00:00,  4.84s/it]

Epoch 50: Training loss: 0.2536306345664302


In [332]:
weight

array([[0.78138312]])

In [328]:
def pred(w,b, X):
    N = len(X)
    predict = []
    for i in range(N):
        z=np.dot(w,X[i])+b
        if sigmoid(z) >= 0.5: # sigmoid(w,x,b) returns 1/(1+exp(-(dot(x,w)+b)))
            predict.append(1)
        else:
            predict.append(0)
    return np.array(predict)
print(1-np.sum(y_train - pred(w,b,X_train))/len(X_train))
print(1-np.sum(y_test  - pred(w,b,X_test))/len(X_test))

NameError: name 'w' is not defined

array([-0.16439526])

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm
